project:
  type: website

website:
  title: "HelloWorld-RBlog"
  navbar:
    left:
     - href: fda.html
       text: Financial Data Analytic
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

